from typing import Protocol

from app.entity.sim_lidar_entity import (
    LidarIngestState,
    MidPushState,
    SimLidarState,
    UdpShipPushState,
)


class SimLidarRepositoryInterface(Protocol):
    def get_state(self) -> SimLidarState: ...
    def set_state(self, state: SimLidarState) -> None: ...
    def get_ingest_state(self) -> LidarIngestState: ...
    def set_ingest_state(self, state: LidarIngestState) -> None: ...
    def get_mid_push_state(self) -> MidPushState: ...
    def set_mid_push_state(self, state: MidPushState) -> None: ...
    def get_udp_ship_push_state(self) -> UdpShipPushState: ...
    def set_udp_ship_push_state(self, state: UdpShipPushState) -> None: ...
