from typing import Protocol

from app.dto.sim_lidar_dto import (
    LidarIngestRequest,
    LidarLatestResponse,
    MidPushStatusResponse,
    StartUdpShipPushRequest,
    StartMidPushRequest,
    StartSimLidarRequest,
    UdpShipPushStatusResponse,
)
from app.entity.sim_lidar_entity import MidPushState, SimLidarState, UdpShipPushState


class SimLidarServiceInterface(Protocol):
    async def start(self, req: StartSimLidarRequest) -> SimLidarState: ...
    async def stop(self) -> SimLidarState: ...
    def status(self) -> SimLidarState: ...
    def ingest(self, req: LidarIngestRequest) -> tuple[int, str]: ...
    def latest_ingest(self) -> LidarLatestResponse: ...
    def latest_for_mid_poll(self) -> LidarLatestResponse: ...
    async def start_mid_push(self, req: StartMidPushRequest) -> MidPushState: ...
    async def stop_mid_push(self) -> MidPushState: ...
    def status_mid_push(self) -> MidPushStatusResponse: ...
    async def start_udp_ship_push(self, req: StartUdpShipPushRequest) -> UdpShipPushState: ...
    async def stop_udp_ship_push(self) -> UdpShipPushState: ...
    def status_udp_ship_push(self) -> UdpShipPushStatusResponse: ...
